### PR TITLE
feat: add support for osx aarch_64

### PR DESCRIPTION
**Pull request by nitinshrm**
* Add logic to deduce aarch_64
* Add print statement to inform user about supported versions
* Add $osname-$osarch in print statement before download

### CODE REVIEW

**Review by timbuethe — APPROVED** [review]

**Comment by lucasls** [comment]
Cool! ✅

**Comment by lucasls** [comment]
@nitinshrm do Linux ARM64 binaries run os OS X?

**Comment by nitinshrm** [comment]
> @nitinshrm do Linux ARM64 binaries run os OS X?

@lucasls I just checked locally and it seems to fail.

**Comment by lucasls** [comment]
@nitinshrm And what about downloading AMD64 if the OS is Mac OS? Afaik it would then run in x64 emulation mode

**Comment by nitinshrm** [comment]
> @nitinshrm And what about downloading AMD64 if the OS is Mac OS? Afaik it would then run in x64 emulation mode

Hi @lucasls sorry for a late response. I haven't tried it yet. Could you point me where I can find the AMD64 binaries?

**Pull request merged**
